---
name: Buld Image
on:
  push:
    tags:
      - '*'

jobs:

  build_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extra_packages:
          - ''
          - gcc
        python_version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: build
        shell: bash
        env:
          DOCKER_BUILDKIT: 1
        run: |
          set -x
          echo ${{ github.ref }} \
            | sed 's|refs/tags/||; s/-/ /' \
            | read -r POETRY_VERSION REVISION
          TAG=py${{ matrix.python_version }}

          if [ ${{ matrix.extra_packages }} ]
          then
            TAG=$TAG$(
              for p in ${{ matrix.extra_packages }}
              do
                echo -n " ${p%=*}"
              done | tr ' ' -)
          fi

          docker build . \
            --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
            --build-arg EXTRA_PACKAGES=${{ matrix.extra_packages }} \
            --build-arg POETRY_VERSION=$POETRY_VERSION \
            --tag aogier/python-poetry:$TAG

          docker login -u aogier -p ${{ secrets.DOCKER_TOKEN }}
          docker push aogier/python-poetry:$TAG

          ADDITIONAL_TAGS=$POETRY_VERSION-$TAG
          if [ $REVISION ]
          then
            ADDITIONAL_TAGS="\
              $ADDITIONAL_TAGS \
              $TAG.$REVISION \
              $POETRY_VERSION-$TAG.$REVISION"
          fi
          for additional_tag in $ADDITIONAL_TAGS; do

            docker tag \
              aogier/python-poetry:$TAG \
              aogier/python-poetry:$additional_tag

            docker push aogier/python-poetry:$additional_tag

          done
