---
name: Check Upstream
on:
  schedule:
    - cron:  '27 4 * * *'

env:
  # xxx
  working_branch: develop

jobs:

  check_upstream:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.working_branch }}
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - uses: fregante/setup-git-user@v2

      - name: build
        shell: bash
        run: |
          set -x

          # get latest tag from upstream
          latest=$(
              curl -sSL \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ github.token }}"\
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/python-poetry/poetry/releases/latest \
              | jq -r .name
          )

          # get tags on current branch's tip
          _tip=$(git log -n1 --format=%H)
          current=$(git tag --contains $_tip)

          echo latest is $latest, mine is $current

          # if no latest on current tip -> build it, bumping tag version if needed
          if ! echo $current | grep $latest; then
              # increment last revision
              new_revision=$(\
                  echo 1 + $(\
                      echo $(\
                          git tag \
                              -l "$latest-*" \
                              --sort=taggerdate \
                          | tail -1) \
                      | awk -F- '{printf("%d", $2)}') \
                  | bc)

              new_tag="$latest-$new_revision"
              git tag "$new_tag"
              git push origin ${{ env.working_branch }} "$new_tag"
          fi
