---
name: Check Upstream
on:
  schedule:
    - cron:  '27 4 * * *'

env:
  # xxx
  working_branch: develop

jobs:

  check_upstream:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.working_branch }}
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - uses: fregante/setup-git-user@v2

      - name: build
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x

          # fetch tags
          git fetch --tags

          # get latest tag from upstream
          latest=$(
              gh api repos/python-poetry/poetry/releases/latest \
              | jq -r .name
          )

          # get tags on current branch's tip
          _tip=$(git log -n1 --format=%H)
          current=$(git tag --contains $_tip)

          echo latest is $latest, mine is $current

          # if no latest on current tip then tag it, bumping tag revision
          # if needed. That will trigger build-and-publish workflow

          if ! echo $current | grep $latest; then

              latest_revision=$(\
                git tag --list "$latest-*" --sort=taggerdate \
                | tail --lines 1 \
                | cut --delimiter - --fields 2 \
              )

              # increment last revision
              new_revision=$(echo ${latest_revision:-0} + 1 | bc)

              new_tag="$latest-$new_revision"
              git tag "$new_tag"
              git push origin ${{ env.working_branch }} "$new_tag"
          fi
